#ifndef __PACMAN_SDL_OPENGL_CONFIG_HEADER_H__
#define __PACMAN_SDL_OPENGL_CONFIG_HEADER_H__

#define CONFIG_OPENGL_LOW_DEF_CIRCLES_TRIANGLES    64
#define CONFIG_OPENGL_HIGH_DEF_CIRCLES_TRIANGLES   1024

#define CONFIG_TILE_BITS        5
#define CONFIG_TILE_SIZE        (1 << CONFIG_TILE_BITS)

#define CONFIG_PACMAN_RADIUS    0.45f

#endif